"""Parse the MicroDuck MJCF into a structured kinematic model.

Source: pollen-robotics/microduck-simulator (HF Space), generated by onshape-to-robot
from Onshape doc 804927696f06d877f3f1803e. Lengths are metres in MJCF; we keep
millimetres everywhere downstream because that is what CAD wants.
"""
from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
MJCF = ROOT / "source" / "robot_allcollisions.xml"
MESHES = ROOT / "source" / "meshes"


def _f(s, default=None):
    if s is None:
        return default
    return np.array([float(x) for x in s.split()], dtype=float)


def quat_to_matrix(q) -> np.ndarray:
    """MuJoCo quaternion (w, x, y, z) -> 3x3 rotation matrix."""
    if q is None:
        return np.eye(3)
    w, x, y, z = q
    n = math.sqrt(w * w + x * x + y * y + z * z)
    if n == 0:
        return np.eye(3)
    w, x, y, z = w / n, x / n, y / n, z / n
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])


def transform(pos_mm, rot) -> np.ndarray:
    T = np.eye(4)
    T[:3, :3] = rot
    T[:3, 3] = pos_mm
    return T


@dataclass
class Instance:
    """One placed occurrence of a mesh inside a body."""
    mesh: str
    T: np.ndarray            # 4x4, millimetres, in body frame
    kind: str = "visual"


@dataclass
class Joint:
    name: str
    axis: np.ndarray
    range: np.ndarray | None
    cls: str | None


@dataclass
class Body:
    name: str
    T_parent: np.ndarray                  # 4x4 mm, relative to parent body
    parent: str | None = None
    mass: float = 0.0                     # kg
    com: np.ndarray | None = None         # mm, body frame
    joint: Joint | None = None
    instances: list[Instance] = field(default_factory=list)
    children: list[str] = field(default_factory=list)
    T_world: np.ndarray = field(default_factory=lambda: np.eye(4))


class Model:
    def __init__(self, path: Path = MJCF):
        self.root = ET.parse(path).getroot()
        self.bodies: dict[str, Body] = {}
        self.order: list[str] = []
        self.mesh_files: dict[str, str] = {}
        for m in self.root.iter("mesh"):
            if m.get("name") and m.get("file"):
                self.mesh_files[m.get("name")] = m.get("file")
            elif m.get("file"):  # onshape-to-robot omits name when it equals the stem
                self.mesh_files[Path(m.get("file")).stem] = m.get("file")
        wb = self.root.find("worldbody")
        for b in wb.findall("body"):
            self._walk(b, None)
        self._propagate()

    def _walk(self, el, parent: str | None):
        name = el.get("name")
        T = transform(_f(el.get("pos"), np.zeros(3)) * 1000.0,
                      quat_to_matrix(_f(el.get("quat"))))
        body = Body(name=name, T_parent=T, parent=parent)

        jel = el.find("joint")
        if jel is not None:
            body.joint = Joint(
                name=jel.get("name"),
                axis=_f(jel.get("axis"), np.array([0.0, 0.0, 1.0])),
                range=_f(jel.get("range")),
                cls=jel.get("class"),
            )
        iel = el.find("inertial")
        if iel is not None:
            body.mass = float(iel.get("mass"))
            body.com = _f(iel.get("pos"), np.zeros(3)) * 1000.0

        for g in el.findall("geom"):
            mesh = g.get("mesh")
            if not mesh:
                continue
            kind = "collision" if g.get("class") == "collision" else "visual"
            if kind == "collision":
                continue  # collision proxies duplicate the visual meshes
            Tg = transform(_f(g.get("pos"), np.zeros(3)) * 1000.0,
                           quat_to_matrix(_f(g.get("quat"))))
            body.instances.append(Instance(mesh=mesh, T=Tg, kind=kind))

        self.bodies[name] = body
        self.order.append(name)
        if parent:
            self.bodies[parent].children.append(name)
        for c in el.findall("body"):
            self._walk(c, name)

    def _propagate(self):
        """Resolve world transforms at the zero pose, with the root at the origin."""
        root = self.order[0]
        self.bodies[root].T_world = np.eye(4)  # drop the 0.12 m spawn height
        for name in self.order[1:]:
            b = self.bodies[name]
            b.T_world = self.bodies[b.parent].T_world @ b.T_parent

    @property
    def joints(self) -> list[Joint]:
        return [b.joint for b in self.bodies.values() if b.joint]

    def total_mass(self) -> float:
        return sum(b.mass for b in self.bodies.values())

    def placements(self) -> list[tuple[str, str, np.ndarray]]:
        """(body, mesh, 4x4 world transform in mm) for every placed mesh."""
        out = []
        for name in self.order:
            b = self.bodies[name]
            for inst in b.instances:
                out.append((name, inst.mesh, b.T_world @ inst.T))
        return out


if __name__ == "__main__":
    m = Model()
    print(f"bodies {len(m.bodies)}  joints {len(m.joints)}  "
          f"mesh instances {len(m.placements())}  unique meshes "
          f"{len({p[1] for p in m.placements()})}")
    print(f"total mass {m.total_mass()*1000:.1f} g")
    for j in m.joints:
        r = "" if j.range is None else f"[{math.degrees(j.range[0]):7.1f} .. {math.degrees(j.range[1]):7.1f}] deg"
        print(f"  {j.name:18s} axis={j.axis} {r}")
    used = {p[1] for p in m.placements()}
    avail = {f.stem for f in MESHES.glob("*.stl")}
    print("\nreferenced but missing:", sorted(used - avail))
    print("downloaded but unused :", sorted(avail - used))
