"""Explain a Blueprint the way an engineer would, in English.

The Blueprint and the verification report are the record of what happened, and
they stay exactly as they are — reproducible, diffable, and the thing to reach
for when something is wrong. But they are a poor way to *read* a design, and a
panel that dumps raw JSON at a user makes a mechanical-engineering system look
like a code generator.

So this narrates. Every sentence is **derived from the frozen Blueprint** — the
part class, the variables, the rationale the model attached to each feature, the
assertions, and what the kernel measured. Nothing is generated by a second model
pass, for one reason that matters more than latency: a summariser can contradict
the geometry it is summarising, and a confident sentence that disagrees with the
part is worse than no sentence. If a fact is not in the Blueprint, it does not
appear here.

The model's own ``<think>`` derivation is deliberately not surfaced as prose. It
is working notes, not an explanation, and it is where the model is least
guarded.
"""

from __future__ import annotations

from typing import Any, Optional

#: Feature types that exist to support other features rather than to be
#: described. A user does not care that a Pad needed a Sketch.
_SCAFFOLDING = {"Body", "Sketch"}

#: PartDesign type -> what it does to material, in plain words.
_ACTION = {
    "Pad": "extrude",
    "Pocket": "cut",
    "Revolution": "revolve",
    "Groove": "cut a revolved groove",
    "Hole": "drill",
    "Loft": "loft",
    "Sweep": "sweep",
    "Fillet": "round",
    "Chamfer": "chamfer",
    "Draft": "draft",
    "Thickness": "hollow",
    "LinearPattern": "pattern",
    "PolarPattern": "pattern about an axis",
    "Mirrored": "mirror",
    "Box": "add a box",
    "Cylinder": "add a cylinder",
    "Sphere": "add a sphere",
    "Cone": "add a cone",
    "Torus": "add a torus",
}

_CHECK_PROSE = {
    "body_volume": "its own closed-form volume matched what the kernel measured",
    "body_volume_profile": "the volume matched the profile area it was built from",
    "body_mesh_converged": "a mesh refinement converged on the same volume",
    "bbox_extent": "the overall extents came out as predicted",
    "feature_volume": "individual feature volumes matched their predictions",
    "solids": "the result is a single connected solid",
    "watertight": "the solid is closed — no open faces",
    "precondition": "the design guards it set for itself hold",
}


def _fmt(v: Any) -> str:
    if isinstance(v, (int, float)) and float(v).is_integer():
        return str(int(v))
    if isinstance(v, float):
        return f"{v:g}"
    return str(v)


def _prose_name(var: str) -> str:
    """Variable name in English, via the packer's vocabulary."""
    try:
        from orion.pack_sft import prose_name

        return prose_name(var)
    except Exception:  # noqa: BLE001 — never let phrasing break a response
        return var.replace("_", " ")


def _readable_class(part_class: str) -> str:
    """'clevis_mount_plus_vent_slot' -> 'clevis mount, with a vent slot'."""
    if not part_class:
        return "part"
    head, _, rest = part_class.partition("_plus_")
    base = head.replace("_", " ")
    if not rest:
        return base
    extras = [e.replace("_", " ") for e in rest.split("_plus_")]
    return f"{base}, with a {' and a '.join(extras)}"


def _was_specified(name: str, value: Any, prompt: str) -> bool:
    """Did the user give this number, or did the model choose it?

    Presentational only, and deliberately conservative — when unsure it reports
    "chosen", because crediting the user with a dimension the model actually
    chose is the more misleading error.

    Two rules earn their keep:

    * Match on **number boundaries**, not substrings. A bare ``in`` test finds
      "2" inside "32".
    * Try the **double only for radii**. "19 mm pivot bore" is the user
      specifying ``bore_r = 9.5``, and missing that would understate what was
      asked for — but applied to every variable it also claims a thickness of 3
      was given whenever "6 mm" appears anywhere.
    """
    import re

    if not prompt or not isinstance(value, (int, float)):
        return False

    candidates = [value]
    # Attachments (att0_*, att1_*) are features the model added on its own, so
    # the diameter reading is not available to them — without this, a
    # lightening-pocket radius of 3 gets credited to the user whenever "6 mm"
    # appears anywhere in the prompt. An exact match still counts.
    is_attachment = name.startswith("att") and name[3:4].isdigit()
    is_radius = name.endswith("_r") or "radius" in _prose_name(name)
    if is_radius and not is_attachment:
        candidates.append(value * 2)  # the user gave it as a diameter

    for candidate in candidates:
        s = _fmt(candidate)
        if s and re.search(rf"(?<![\d.]){re.escape(s)}(?![\d.])", prompt):
            return True
    return False


def build(bundle: dict, prompt: str = "") -> Optional[dict]:
    """Narrative for a successful design bundle, or None if there is nothing
    to narrate."""
    bp = bundle.get("blueprint") or {}
    if not bp:
        return None

    part_class = bp.get("part_class") or bundle.get("part_class") or ""
    variables: dict = bp.get("variables") or {}
    plan = bp.get("design_plan") or {}
    template = bp.get("template") or {}
    report = bundle.get("verification") or {}
    stats = bundle.get("stats") or {}

    sections: list[dict] = []

    # ---- 1. what it understood ------------------------------------------- #
    given, chosen = [], []
    for name, value in variables.items():
        entry = f"{_prose_name(name)} {_fmt(value)} mm"
        (given if _was_specified(name, value, prompt) else chosen).append(entry)

    interp = [f"Read this as a **{_readable_class(part_class)}**."]
    if given:
        interp.append("Taken from your description: " + ", ".join(given) + ".")
    if chosen:
        interp.append(
            (
                "Chosen to complete the design: "
                if given
                else "Dimensions chosen for the design: "
            )
            + ", ".join(chosen)
            + "."
        )
    datums = bp.get("datums") or {}
    if datums:
        interp.append(
            "Datums set as " + ", ".join(f"{k} = {v}" for k, v in datums.items()) + "."
        )
    sections.append({"title": "Interpretation", "body": " ".join(interp)})

    # ---- 2. how it was built --------------------------------------------- #
    steps = []
    for feat in template.get("features") or []:
        ftype = feat.get("type", "")
        if ftype in _SCAFFOLDING:
            continue
        action = _ACTION.get(ftype, ftype.lower())
        label = (feat.get("rationale") or feat.get("id", "")).strip()
        steps.append(
            {"action": action, "detail": label, "id": feat.get("id", ""), "type": ftype}
        )
    if steps:
        sections.append(
            {
                "title": "Feature sequence",
                "body": "Built in this order, each feature referencing the one "
                "before it, so the model stays parametric and editable.",
                "items": [
                    f"**{s['action'].capitalize()}** — {s['detail']}" for s in steps
                ],
            }
        )

    # ---- 3. why it is shaped this way ------------------------------------ #
    reasons = [
        d.get("why", "").strip() for d in (plan.get("derivation") or []) if d.get("why")
    ]
    if reasons:
        sections.append(
            {
                "title": "Design intent",
                "body": "The reasoning behind the shape, and the terms that make "
                "up its volume:",
                "items": reasons,
            }
        )

    # ---- 4. what was actually proved ------------------------------------- #
    checks = report.get("checks") or []
    failed = report.get("failed") or []
    verdict = report.get("verdict", "unproven")

    kinds = []
    for c in checks:
        kind = str(c.get("id", "")).split(":", 1)[0]
        phrase = _CHECK_PROSE.get(kind)
        if phrase and phrase not in kinds:
            kinds.append(phrase)

    if verdict == "verified" and kinds:
        body = (
            "Before any geometry existed, the design committed to what it "
            "should measure. It was then built and measured, and " + _join(kinds) + "."
        )
        if stats.get("volume_mm3"):
            body += f" Final volume {stats['volume_mm3'] / 1000:.3f} cm³" + (
                f", envelope {'×'.join(str(round(v)) for v in stats['bbox_mm'])} mm."
                if stats.get("bbox_mm")
                else "."
            )
    elif failed:
        body = (
            "This part is **not** correct as drawn. "
            + _join(
                [
                    f"{c.get('label', 'a check')} failed — " f"{c.get('detail', '')}"
                    for c in failed
                ]
            )
            + ". It is being shown so the failure is visible, not because "
            "it is usable."
        )
    else:
        body = (
            "Nothing failed, but nothing was proved either — no check "
            "produced evidence, so treat this geometry as unverified."
        )

    sections.append({"title": "Verification", "body": body})

    return {
        "headline": _headline(part_class, stats, verdict),
        "sections": sections,
        "verdict": verdict,
    }


def _headline(part_class: str, stats: dict, verdict: str) -> str:
    name = _readable_class(part_class)
    bits = [name[0].upper() + name[1:] if name else "Part"]
    if stats.get("bbox_mm"):
        bits.append("×".join(str(round(v)) for v in stats["bbox_mm"]) + " mm")
    if stats.get("volume_mm3"):
        bits.append(f"{stats['volume_mm3'] / 1000:.2f} cm³")
    line = " · ".join(bits)
    return line if verdict == "verified" else f"{line} — {verdict}"


def _join(items: list[str]) -> str:
    items = [i for i in items if i]
    if not items:
        return ""
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]
