"""
Construction Plan - The Intelligence Boundary

==============================================================================
ARCHITECTURE PRINCIPLE: ConstructionPlan = Intelligence Boundary
==============================================================================

This is the SINGLE MOST IMPORTANT architectural component.
All reasoning, intent, and design decisions MUST be captured here.

WHAT CONSTRUCTIONPLAN IS:
- The ONLY place for design reasoning and intent
- Persisted for traceability and learning
- Inspectable by users for approval/rejection
- Editable for iterative refinement
- The upstream source for FeatureGraph generation

WHAT CONSTRUCTIONPLAN IS NOT:
- NOT executable (that's FeatureGraphIR)
- NOT geometry (that's compiler output)
- NOT ambiguous (open questions must be resolved)

PIPELINE POSITION:
    User Prompt
         |
         v
    DesignIntent (what is it?)
         |
         v
    ConstructionPlan (THIS FILE) <-- INTELLIGENCE BOUNDARY
         |
         v
    FeatureGraphIR (exact ops - execution only)
         |
         v
    Compiler
         |
         v
    Geometry

HARD CONTRACT:
    FeatureGraph should NEVER exist without a ConstructionPlan upstream.

Version: 2.0 (First-Class Domain Object)
"""
from typing import List, Dict, Optional, Literal, Any
from pydantic import BaseModel, Field, field_validator, model_validator
from enum import Enum
from datetime import datetime
import uuid
import json
import hashlib


# =============================================================================
# Plan Status (Lifecycle)
# =============================================================================

class PlanStatus(str, Enum):
    """Lifecycle status of a ConstructionPlan."""
    DRAFT = "draft"           # Initial state, may have open questions
    PENDING_REVIEW = "pending_review"  # Ready for user approval
    APPROVED = "approved"     # User approved, ready for FeatureGraph generation
    REJECTED = "rejected"     # User rejected, needs revision
    EXECUTED = "executed"     # FeatureGraph generated successfully
    FAILED = "failed"         # FeatureGraph generation failed


class PlanSource(str, Enum):
    """Source of plan generation."""
    LLM = "llm"              # Generated by LLM
    HEURISTIC = "heuristic"  # Generated by rule-based system
    USER = "user"            # Created/edited by user
    TEMPLATE = "template"    # Generated from template


# =============================================================================
# Parameter with Intelligence
# =============================================================================

class PlanParameter(BaseModel):
    """
    A parameter in the construction plan with full context.

    This includes:
    - Unit and bounds for validation
    - Dependencies for constraint propagation
    - Semantic description for user understanding
    - Reasoning for why this value was chosen
    """
    unit: Literal["mm", "inch", "deg", "rad"] = Field(
        "mm",
        description="Unit of measurement"
    )
    default: float = Field(
        ...,
        description="Default value"
    )
    depends_on: Optional[str] = Field(
        None,
        description="Parameter this depends on (for constraint propagation)"
    )
    min_value: Optional[float] = Field(
        None,
        description="Minimum valid value"
    )
    max_value: Optional[float] = Field(
        None,
        description="Maximum valid value"
    )

    # Intelligence fields (for reasoning, NOT for execution)
    semantic_name: Optional[str] = Field(
        None,
        description="Human-readable name (e.g., 'Overall Height')"
    )
    reasoning: Optional[str] = Field(
        None,
        description="Why this value was chosen (for traceability)"
    )
    is_critical: bool = Field(
        False,
        description="True if this parameter is critical for design intent"
    )

    @field_validator('default')
    @classmethod
    def validate_default_positive(cls, v):
        """Most CAD parameters should be non-negative."""
        if v < 0:
            raise ValueError(f"Parameter default must be non-negative, got {v}")
        return v

    def validate_value(self, value: float) -> List[str]:
        """Validate a specific value against constraints."""
        errors = []
        if self.min_value is not None and value < self.min_value:
            errors.append(f"Value {value} below minimum {self.min_value}")
        if self.max_value is not None and value > self.max_value:
            errors.append(f"Value {value} above maximum {self.max_value}")
        return errors


# =============================================================================
# Construction Step (Ordered Operation)
# =============================================================================

class ConstructionStep(BaseModel):
    """
    A single step in the construction sequence.

    More structured than a plain string, enables:
    - Feature type mapping for FeatureGraph generation
    - Validation before execution
    - User-friendly display
    """
    order: int = Field(
        ...,
        description="Step order (1-indexed)"
    )
    description: str = Field(
        ...,
        description="Human-readable description of the step"
    )
    feature_type: Optional[str] = Field(
        None,
        description="Mapped feature type (extrude, fillet, etc.)"
    )
    sketch_required: bool = Field(
        False,
        description="True if this step requires a sketch"
    )
    parameters_used: List[str] = Field(
        default_factory=list,
        description="Names of parameters used in this step"
    )
    reasoning: Optional[str] = Field(
        None,
        description="Why this step is needed"
    )


# =============================================================================
# ConstructionPlan (First-Class Domain Object)
# =============================================================================

class ConstructionPlan(BaseModel):
    """
    The Intelligence Boundary - All design reasoning lives here.

    This is a FIRST-CLASS DOMAIN OBJECT that is:
    1. PERSISTED - saved to disk for traceability
    2. INSPECTABLE - users can view and understand the plan
    3. REJECTABLE - users can reject bad plans
    4. EDITABLE - users can modify plans before execution

    HARD CONTRACT:
        FeatureGraph should NEVER exist without a ConstructionPlan.

    Example:
        plan = ConstructionPlan(
            id="plan_abc123",
            prompt="Create a 50mm cube with 5mm fillets",
            status=PlanStatus.DRAFT,
            construction_sequence=[
                ConstructionStep(order=1, description="Create base sketch"),
                ConstructionStep(order=2, description="Extrude to height"),
                ConstructionStep(order=3, description="Apply fillets")
            ],
            parameters={"size": PlanParameter(default=50.0, unit="mm")},
            assumptions=["Centered on origin"],
            design_rationale="Simple filleted box per user request"
        )
    """

    # ==========================================================================
    # Identity & Lifecycle
    # ==========================================================================

    id: str = Field(
        default_factory=lambda: f"plan_{uuid.uuid4().hex[:12]}",
        description="Unique plan identifier for traceability"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Plan creation timestamp"
    )
    updated_at: Optional[datetime] = Field(
        None,
        description="Last update timestamp"
    )
    status: PlanStatus = Field(
        PlanStatus.DRAFT,
        description="Current lifecycle status"
    )
    source: PlanSource = Field(
        PlanSource.HEURISTIC,
        description="How this plan was generated"
    )
    version: int = Field(
        1,
        description="Plan version (incremented on edits)"
    )

    # ==========================================================================
    # Original Context
    # ==========================================================================

    prompt: str = Field(
        "",
        description="Original user prompt (for traceability)"
    )
    intent_id: Optional[str] = Field(
        None,
        description="ID of upstream DesignIntent (if applicable)"
    )

    # ==========================================================================
    # Construction Specification
    # ==========================================================================

    base_reference: str = Field(
        "XY plane",
        description="Reference plane or origin for construction"
    )
    construction_sequence: List[ConstructionStep] = Field(
        default_factory=list,
        description="Ordered construction steps"
    )
    parameters: Dict[str, PlanParameter] = Field(
        default_factory=dict,
        description="Named parameters with full context"
    )

    # ==========================================================================
    # Intelligence Fields (Reasoning - NOT for execution)
    # ==========================================================================

    assumptions: List[str] = Field(
        default_factory=list,
        description="Assumptions made during planning"
    )
    open_questions: List[str] = Field(
        default_factory=list,
        description="Questions requiring user clarification"
    )
    manufacturing_constraints: List[str] = Field(
        default_factory=list,
        description="Manufacturing constraints to consider"
    )
    design_rationale: Optional[str] = Field(
        None,
        description="Brief explanation of design choices"
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="Warnings about potential issues"
    )

    # ==========================================================================
    # Execution Tracking
    # ==========================================================================

    feature_graph_id: Optional[str] = Field(
        None,
        description="ID of generated FeatureGraph (after execution)"
    )
    execution_error: Optional[str] = Field(
        None,
        description="Error message if execution failed"
    )

    # ==========================================================================
    # Validators
    # ==========================================================================

    @model_validator(mode='after')
    def validate_construction_sequence(self):
        """Ensure construction sequence is properly ordered."""
        if self.construction_sequence:
            orders = [step.order for step in self.construction_sequence]
            if len(orders) != len(set(orders)):
                raise ValueError("Construction steps must have unique order values")
        return self

    @model_validator(mode='after')
    def validate_parameter_dependencies(self):
        """Ensure parameter dependencies are valid."""
        param_names = set(self.parameters.keys())
        for name, param in self.parameters.items():
            if param.depends_on:
                if param.depends_on == name:
                    raise ValueError(
                        f"Parameter '{name}' has circular dependency"
                    )
                if param.depends_on not in param_names:
                    raise ValueError(
                        f"Parameter '{name}' depends on unknown '{param.depends_on}'"
                    )
        return self

    # ==========================================================================
    # Lifecycle Methods
    # ==========================================================================

    def has_open_questions(self) -> bool:
        """Check if plan has unresolved questions."""
        return len(self.open_questions) > 0

    def is_ready_for_execution(self) -> bool:
        """Check if plan is ready for FeatureGraph generation."""
        return (
            self.status == PlanStatus.APPROVED and
            not self.has_open_questions() and
            len(self.construction_sequence) > 0
        )

    def approve(self) -> "ConstructionPlan":
        """Mark plan as approved (returns new instance)."""
        if self.has_open_questions():
            raise ValueError("Cannot approve plan with open questions")
        return self.model_copy(update={
            "status": PlanStatus.APPROVED,
            "updated_at": datetime.utcnow()
        })

    def reject(self, reason: str) -> "ConstructionPlan":
        """Mark plan as rejected with reason."""
        return self.model_copy(update={
            "status": PlanStatus.REJECTED,
            "execution_error": reason,
            "updated_at": datetime.utcnow()
        })

    def mark_executed(self, feature_graph_id: str) -> "ConstructionPlan":
        """Mark plan as successfully executed."""
        return self.model_copy(update={
            "status": PlanStatus.EXECUTED,
            "feature_graph_id": feature_graph_id,
            "updated_at": datetime.utcnow()
        })

    def mark_failed(self, error: str) -> "ConstructionPlan":
        """Mark plan as failed."""
        return self.model_copy(update={
            "status": PlanStatus.FAILED,
            "execution_error": error,
            "updated_at": datetime.utcnow()
        })

    # ==========================================================================
    # Validation Methods
    # ==========================================================================

    def validate_plan(self) -> List[str]:
        """
        Validate plan for completeness and consistency.

        Returns:
            List of validation errors (empty if valid)
        """
        errors = []

        # Check construction sequence
        if not self.construction_sequence:
            errors.append("Construction sequence cannot be empty")

        # Check parameter bounds
        for name, param in self.parameters.items():
            if param.min_value is not None and param.max_value is not None:
                if param.min_value > param.max_value:
                    errors.append(
                        f"Parameter '{name}' has invalid range (min > max)"
                    )
            if param.min_value is not None and param.default < param.min_value:
                errors.append(f"Parameter '{name}' default below minimum")
            if param.max_value is not None and param.default > param.max_value:
                errors.append(f"Parameter '{name}' default above maximum")

        # Check step parameter references
        param_names = set(self.parameters.keys())
        for step in self.construction_sequence:
            for param_ref in step.parameters_used:
                if param_ref not in param_names:
                    errors.append(
                        f"Step {step.order} references unknown parameter '{param_ref}'"
                    )

        return errors

    def is_valid(self) -> bool:
        """Check if plan passes all validation."""
        return len(self.validate_plan()) == 0

    # ==========================================================================
    # Parameter Resolution
    # ==========================================================================

    def get_resolved_parameters(self) -> Dict[str, float]:
        """
        Resolve all parameters to concrete float values.

        Returns:
            Dict mapping parameter names to resolved values
        """
        resolved = {}

        # First pass: non-dependent parameters
        for name, param in self.parameters.items():
            if not param.depends_on:
                resolved[name] = param.default

        # Second pass: dependent parameters (simple linear)
        for name, param in self.parameters.items():
            if param.depends_on and param.depends_on in resolved:
                resolved[name] = param.default
            elif name not in resolved:
                resolved[name] = param.default

        return resolved

    # ==========================================================================
    # LLM Context Generation
    # ==========================================================================

    def to_prompt_context(self) -> str:
        """
        Convert plan to prompt context for LLM FeatureGraph generation.

        This is what the LLM sees when generating FeatureGraph.
        """
        lines = [
            f"Plan ID: {self.id}",
            f"Base Reference: {self.base_reference}",
            "",
            "Construction Sequence:",
        ]

        for step in sorted(self.construction_sequence, key=lambda s: s.order):
            feature_hint = f" [{step.feature_type}]" if step.feature_type else ""
            lines.append(f"  {step.order}. {step.description}{feature_hint}")

        if self.parameters:
            lines.append("")
            lines.append("Parameters:")
            for name, param in self.parameters.items():
                dep = f" (depends on {param.depends_on})" if param.depends_on else ""
                lines.append(f"  - {name}: {param.default}{param.unit}{dep}")

        if self.assumptions:
            lines.append("")
            lines.append("Assumptions:")
            for assumption in self.assumptions:
                lines.append(f"  - {assumption}")

        if self.manufacturing_constraints:
            lines.append("")
            lines.append("Manufacturing Constraints:")
            for constraint in self.manufacturing_constraints:
                lines.append(f"  - {constraint}")

        return "\n".join(lines)

    # ==========================================================================
    # Persistence & Serialization
    # ==========================================================================

    def compute_hash(self) -> str:
        """Compute deterministic hash for caching/deduplication."""
        # Only hash the essential content, not metadata
        content = {
            "base_reference": self.base_reference,
            "construction_sequence": [s.model_dump() for s in self.construction_sequence],
            "parameters": {k: v.model_dump() for k, v in self.parameters.items()},
        }
        content_str = json.dumps(content, sort_keys=True)
        return hashlib.sha256(content_str.encode()).hexdigest()[:16]

    def to_persistence_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for persistence.

        Includes all fields for full reconstruction.
        """
        return {
            "id": self.id,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "status": self.status.value,
            "source": self.source.value,
            "version": self.version,
            "prompt": self.prompt,
            "intent_id": self.intent_id,
            "base_reference": self.base_reference,
            "construction_sequence": [s.model_dump() for s in self.construction_sequence],
            "parameters": {k: v.model_dump() for k, v in self.parameters.items()},
            "assumptions": self.assumptions,
            "open_questions": self.open_questions,
            "manufacturing_constraints": self.manufacturing_constraints,
            "design_rationale": self.design_rationale,
            "warnings": self.warnings,
            "feature_graph_id": self.feature_graph_id,
            "execution_error": self.execution_error,
            "content_hash": self.compute_hash()
        }

    @classmethod
    def from_persistence_dict(cls, data: Dict[str, Any]) -> "ConstructionPlan":
        """Reconstruct from persistence dictionary."""
        # Parse timestamps
        created_at = datetime.fromisoformat(data["created_at"])
        updated_at = (
            datetime.fromisoformat(data["updated_at"])
            if data.get("updated_at") else None
        )

        # Parse construction sequence
        construction_sequence = [
            ConstructionStep(**step)
            for step in data.get("construction_sequence", [])
        ]

        # Parse parameters
        parameters = {
            name: PlanParameter(**param)
            for name, param in data.get("parameters", {}).items()
        }

        return cls(
            id=data["id"],
            created_at=created_at,
            updated_at=updated_at,
            status=PlanStatus(data["status"]),
            source=PlanSource(data["source"]),
            version=data.get("version", 1),
            prompt=data.get("prompt", ""),
            intent_id=data.get("intent_id"),
            base_reference=data.get("base_reference", "XY plane"),
            construction_sequence=construction_sequence,
            parameters=parameters,
            assumptions=data.get("assumptions", []),
            open_questions=data.get("open_questions", []),
            manufacturing_constraints=data.get("manufacturing_constraints", []),
            design_rationale=data.get("design_rationale"),
            warnings=data.get("warnings", []),
            feature_graph_id=data.get("feature_graph_id"),
            execution_error=data.get("execution_error"),
        )

    # ==========================================================================
    # Editing Support
    # ==========================================================================

    def update_parameter(
        self,
        name: str,
        value: float,
        reason: Optional[str] = None
    ) -> "ConstructionPlan":
        """
        Update a parameter value (returns new instance).

        Args:
            name: Parameter name
            value: New value
            reason: Optional reason for the change
        """
        if name not in self.parameters:
            raise ValueError(f"Unknown parameter: {name}")

        new_params = dict(self.parameters)
        old_param = new_params[name]

        # Validate new value
        errors = old_param.validate_value(value)
        if errors:
            raise ValueError(f"Invalid value: {errors}")

        new_params[name] = old_param.model_copy(update={
            "default": value,
            "reasoning": reason or old_param.reasoning
        })

        return self.model_copy(update={
            "parameters": new_params,
            "version": self.version + 1,
            "updated_at": datetime.utcnow()
        })

    def add_step(
        self,
        description: str,
        feature_type: Optional[str] = None,
        parameters_used: Optional[List[str]] = None
    ) -> "ConstructionPlan":
        """Add a construction step (returns new instance)."""
        new_order = (
            max(s.order for s in self.construction_sequence) + 1
            if self.construction_sequence else 1
        )

        new_step = ConstructionStep(
            order=new_order,
            description=description,
            feature_type=feature_type,
            parameters_used=parameters_used or []
        )

        return self.model_copy(update={
            "construction_sequence": self.construction_sequence + [new_step],
            "version": self.version + 1,
            "updated_at": datetime.utcnow()
        })

    def resolve_question(
        self,
        question: str,
        answer: str
    ) -> "ConstructionPlan":
        """
        Resolve an open question (returns new instance).

        The answer is added to assumptions.
        """
        if question not in self.open_questions:
            raise ValueError(f"Question not found: {question}")

        new_questions = [q for q in self.open_questions if q != question]
        new_assumptions = self.assumptions + [f"[Resolved] {question}: {answer}"]

        return self.model_copy(update={
            "open_questions": new_questions,
            "assumptions": new_assumptions,
            "version": self.version + 1,
            "updated_at": datetime.utcnow()
        })


# =============================================================================
# Plan Persistence Service
# =============================================================================

class PlanPersistence:
    """
    Service for persisting and retrieving ConstructionPlans.

    This ensures plans are always saved for:
    - Traceability
    - Active learning
    - User review
    """

    def __init__(self, storage_dir: str = "data/plans"):
        """Initialize with storage directory."""
        from pathlib import Path
        self.storage_dir = Path(storage_dir)
        self.storage_dir.mkdir(parents=True, exist_ok=True)

    def save(self, plan: ConstructionPlan) -> str:
        """
        Save a plan to disk.

        Returns:
            Path to saved file
        """
        filename = f"{plan.id}.json"
        filepath = self.storage_dir / filename

        with open(filepath, 'w') as f:
            json.dump(plan.to_persistence_dict(), f, indent=2)

        return str(filepath)

    def load(self, plan_id: str) -> Optional[ConstructionPlan]:
        """
        Load a plan by ID.

        Returns:
            ConstructionPlan or None if not found
        """
        filename = f"{plan_id}.json"
        filepath = self.storage_dir / filename

        if not filepath.exists():
            return None

        with open(filepath, 'r') as f:
            data = json.load(f)

        return ConstructionPlan.from_persistence_dict(data)

    def list_plans(
        self,
        status: Optional[PlanStatus] = None
    ) -> List[str]:
        """
        List plan IDs, optionally filtered by status.

        Returns:
            List of plan IDs
        """
        plan_ids = []

        for filepath in self.storage_dir.glob("*.json"):
            if status is not None:
                with open(filepath, 'r') as f:
                    data = json.load(f)
                if data.get("status") == status.value:
                    plan_ids.append(filepath.stem)
            else:
                plan_ids.append(filepath.stem)

        return plan_ids
