"""
Onshape Compiler - FeatureGraph v1 → FeatureScript

Translates the Canonical Feature Graph (CFG) into Onshape's FeatureScript language.
This allows the AI to generate fully parametric, editable Onshape documents, not just ""dumb"" imported geometry.

Architecture:
    FeatureGraph → FeatureScript String → Onshape API (via separate client)

Mapping:
    Parameters → FeatureScript variables (var x = 10 * mm)
    Sketches   → newSketch(), skRectangle(), skCircle()
    Constraints→ skConstraint()
    Features   → opExtrude(), opFillet(), etc.
"""
import logging
from typing import List, Dict, Any
from app.domain.feature_graph import FeatureGraph, Sketch, Feature, SketchEntity, SketchConstraint

logger = logging.getLogger(__name__)


class OnshapeCompiler:
    """
    Compiles FeatureGraph v1 to FeatureScript.
    
    Generates code that can be executed inside an Onshape FeatureStudio
    to reconstruct the parametric model exactly.
    """
    
    def compile(self, cfg: FeatureGraph) -> str:
        """
        Compile FeatureGraph to a complete FeatureScript feature/module.
        
        Args:
            cfg: Canonical Feature Graph
            
        Returns:
            String containing the full FeatureScript code
        """
        logger.info(f"Compiling FeatureGraph to FeatureScript (CFG v1)")
        
        fs = []
        
        # 1. Header & Imports
        fs.append("// Generated by OrionFlow AI")
        fs.append("FeatureScript 1400;")
        fs.append('import(path : "onshape/std/geometry.fs", version : "1400.0");')
        fs.append("")
        
        # 2. Define the Feature function
        # We wrap everything in a custom feature for portability
        fs.append("annotation { \"Feature Type Name\" : \"OrionFlow Generated\" }")
        fs.append("export const orionFlowModel = defineFeature(function(context is Context, id is Id, definition is map)")
        fs.append("    precondition")
        fs.append("    {")
        # Define UI inputs for parameters (allows editing in Onshape UI!)
        for name, value in cfg.parameters.items():
            fs.append(f"        annotation {{ \"Name\" : \"{name}\" }}")
            fs.append(f"        isLength(definition.{name}, {{ \"Default\" : {value} * millimeter }});")
        fs.append("    }")
        fs.append("    {")
        
        # 3. Parameters -> Variables
        # Map definition inputs to local variables for cleaner code
        fs.append("        // Parameters")
        for name in cfg.parameters:
             fs.append(f"        var {name} = definition.{name};")
        fs.append("")
        
        # 4. Sketches
        fs.append("        // Sketches")
        for sketch in cfg.sketches:
            fs.extend(self._emit_sketch(sketch))
            fs.append("")
            
        # 5. Features (Solids)
        fs.append("        // Features")
        for feature in cfg.features:
            fs.extend(self._emit_feature(feature))
            fs.append("")
            
        fs.append("    });")
        
        return "\n".join(fs)

    def _emit_sketch(self, sketch: Sketch) -> List[str]:
        """Generate FeatureScript for a single sketch."""
        lines = []
        s_id = clean_id(sketch.id)
        
        # Resolve Plane
        plane_map = {
            "XY": "plane(vector(0, 0, 0) * meter, vector(0, 0, 1))", # Standard Top
            "XZ": "plane(vector(0, 0, 0) * meter, vector(0, 1, 0))", # Front
            "YZ": "plane(vector(0, 0, 0) * meter, vector(1, 0, 0))"  # Right
        }
        plane_code = plane_map.get(sketch.plane, plane_map["XY"])
        
        # Create Sketch
        lines.append(f"        var {s_id} = newSketch(context, id + \"{s_id}\", {{")
        lines.append(f"            \"sketchPlane\" : {plane_code}")
        lines.append("        });")
        
        # Add Entities
        for entity in sketch.entities:
            lines.extend(self._emit_sketch_entity(s_id, entity))
            
        # Add Constraints
        for const in sketch.constraints:
            lines.extend(self._emit_constraint(s_id, const))
            
        # Solve Sketch
        lines.append(f"        skSolve(context, id + \"{s_id}\", {{")
        lines.append(f"            \"sketch\" : {s_id}")
        lines.append("        });")
        
        return lines

    def _emit_sketch_entity(self, sketch_var: str, entity: SketchEntity) -> List[str]:
        """Generate code for sketch entities (rectangle, circle, etc)."""
        lines = []
        e_id = clean_id(entity.id)
        
        # Helper to format params
        def val(k): return _fmt_val(entity.params.get(k))
        
        if entity.type == "rectangle":
            # skRectangle(sketch, "rectId", { "firstCorner": ..., "secondCorner": ... })
            # Simplified: centered rectangle logic
            # FeatureScript usually uses corner-to-corner or center-and-corner
            width = entity.params.get("width")
            height = entity.params.get("height")
            
            lines.append(f"        skRectangle(context, id + \"{sketch_var}\" + \"{e_id}\", {{")
            lines.append(f"            \"sketch\" : {sketch_var},")
            lines.append(f"            \"center\" : vector(0, 0) * millimeter,")
            lines.append(f"            \"width\" : {val('width')} * millimeter,")
            lines.append(f"            \"height\" : {val('height')} * millimeter")
            # Note: standard skRectangle might take different params dependent on std version
            # Using generic signature for intent
            lines.append("        });")
            
        elif entity.type == "circle":
            lines.append(f"        skCircle(context, id + \"{sketch_var}\" + \"{e_id}\", {{")
            lines.append(f"            \"sketch\" : {sketch_var},")
            lines.append(f"            \"center\" : vector(0, 0) * millimeter,")
            lines.append(f"            \"radius\" : {val('radius')} * millimeter")
            lines.append("        });")
            
        return lines
        
    def _emit_constraint(self, sketch_var: str, constraint: SketchConstraint) -> List[str]:
        """Generate sketch constraints."""
        # This is strictly for intent - many built-in constraints are implicit in sk* calls
        lines = []
        # Support common constraints
        # mapping: "vertical" -> ConstraintType.VERTICAL
        # For now, we'll comment them out or emit a generic constraint call placeholder
        # as FeatureScript constraint syntax is verbose
        
        # Example: skConstraint(sketch, "id", { "constraintType" : ConstraintType.VERTICAL, ... })
        return lines

    def _emit_feature(self, feature: Feature) -> List[str]:
        """Generate code for 3D operations (extrude, fillet)."""
        lines = []
        f_id = clean_id(feature.id)
        
        def val(k): return _fmt_val(feature.params.get(k))
        
        if feature.type == "extrude":
            sketch_ref = clean_id(feature.sketch)
            if not sketch_ref: return []
            
            lines.append(f"        opExtrude(context, id + \"{f_id}\", {{")
            lines.append(f"            \"entities\" : qSketchRegion(id + \"{sketch_ref}\"),")
            lines.append(f"            \"direction\" : evOwnerSketchPlane(context, {{ \"entity\" : qSketchRegion(id + \"{sketch_ref}\") }}).normal,")
            lines.append(f"            \"endBound\" : BoundingType.BLIND,")
            lines.append(f"            \"endDepth\" : {val('depth')} * millimeter")
            lines.append("        });")
            
        elif feature.type == "fillet":
             # Apply to all edges generated by the parent feature
             # Heuristic: if depends_on has [feat_id], fillet that feature's edges
             parent_ids = feature.depends_on
             query = "qEverything(EntityType.EDGE)" # Default dangerous fallback
             
             if parent_ids:
                 # Clean parent ID
                 p_id = clean_id(parent_ids[0])
                 # Query edges created by that operation
                 query = f"qCreatedBy(id + \"{p_id}\", EntityType.EDGE)"
             
             lines.append(f"        opFillet(context, id + \"{f_id}\", {{")
             lines.append(f"            \"entities\" : {query},")
             lines.append(f"            \"radius\" : {val('radius')} * millimeter")
             lines.append("        });")
             
        elif feature.type == "chamfer":
             parent_ids = feature.depends_on
             query = f"qCreatedBy(id + \"{clean_id(parent_ids[0])}\", EntityType.EDGE)" if parent_ids else "qEverything(EntityType.EDGE)"
             
             lines.append(f"        opChamfer(context, id + \"{f_id}\", {{")
             lines.append(f"            \"entities\" : {query},")
             lines.append(f"            \"offset1\" : {val('distance')} * millimeter")
             lines.append("        });")
             
        return lines


# Helpers 

def clean_id(raw_id: str) -> str:
    """Sanitize IDs for FeatureScript variable names."""
    if not raw_id: return "unknown"
    return raw_id.replace("-", "_").replace(" ", "_").replace(".", "_")

def _fmt_val(v: Any) -> str:
    """Format value for FeatureScript. Handle string params ($name) and floats."""
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str) and v.startswith("$"):
        return v[1:] # Return variable name directly
    return "0" # Fallback
